### ISSUE TITLE
請教關於 humix-conversation-module failed 的問題

### ISSUE THREAD

**Issue by ChouYuWei** [project-humix/humix-think#11]
按照 Humix Installation Guide的步驟，到了Install Humix Sense這部分，執行 4. Start humix sense 
 ~/start.sh 的時候，一開始都還正常，不過顯示完以下這一行訊息之後，
[ INFO] Humix-Sense: subscribing topic:humix.sense.humix-conversation-module.event.stt
這裡開始顯示錯誤：
[ERROR] Humix-Sense:
[ INFO] Humix-Sense: process for module [/home/pi/humix-sense/modules/core/humix-conversation-module] spawned
[ERROR] Humix-Sense: connection with module humix-conversation-module failed
[ERROR] Humix-Sense: connection with module humix-conversation-module failed
接著開始重複開始顯示這幾行的錯誤訊息，不知道如何解決?

**Comment by jeffffrey** [comment]
應該是設定的問題，你可以貼  ~/.humix/humix-conversation-module.log 到這邊我看一下嗎？還有 ~/.humix/config.js

thanks.

**Comment by ChouYuWei** [comment]
先謝謝您的回覆。
/home/pi/humix-sense/modules/core/humix-conversation-module/ 下的 config.js
module.exports = {
    lang: 'cht', // 'en', 'cht' or 'chs'
    'stt-engine': 'watson', // 'watson' or 'google',
    'tts-engine': 'itri', // 'watson' or 'itri' or 'iflytek'
    stt: {
        watson: {
            username: 'xxx',
            passwd: 'xxx'
        },
        google: {
            username: 'xxxxx',
            passwd: '',
            googleCredentialFile: '', //the location of your google auth credential file.
            googleProjectName: '', //the project name which create your credential file.
            googleLan: 'cmn-Hant-TW', // en-Us or cmn-Hant-TW
        }
    },
    tts: {
        watson: {
            username: 'xxx',
            passwd: 'xxx'
        },
        iflytek: {
            appid: '<app_id>'
        },
        itri: {
            username: 'hugh',
            passwd: 'xxx',
            speaker: 'bruce',
        }
    }
};

username、passwd的部分，在這裡我拿掉了。

humix-conversation-module.log的部分，我沒找到，有npm-debug.log這個log檔，內容如下：
0 info it worked if it ends with ok
1 verbose cli [ '/home/pi/.nvm/versions/node/v4.2.6/bin/node',
1 verbose cli   '/home/pi/.nvm/versions/node/v4.2.6/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart humix-conversation-module@0.1.0
6 info start humix-conversation-module@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info humix-conversation-module@0.1.0 Failed to exec start script
9 verbose stack Error: humix-conversation-module@0.1.0 start: `node humix-conversation.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/home/pi/.nvm/versions/node/v4.2.6/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/home/pi/.nvm/versions/node/v4.2.6/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid humix-conversation-module@0.1.0
11 verbose cwd /home/pi/humix-sense/modules/core/humix-conversation-module
12 error Linux 4.4.11-v7+
13 error argv "/home/pi/.nvm/versions/node/v4.2.6/bin/node" "/home/pi/.nvm/versions/node/v4.2.6/bin/npm" "start"
14 error node v4.2.6
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error humix-conversation-module@0.1.0 start: `node humix-conversation.js`
17 error Exit status 1
18 error Failed at the humix-conversation-module@0.1.0 start script 'node humix-conversation.js'.
18 error This is most likely a problem with the humix-conversation-module package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node humix-conversation.js
18 error You can get their info via:
18 error     npm owner ls humix-conversation-module
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

麻煩您了，謝謝。

**Comment by jeffffrey** [comment]
看起來在起conversation module的時候有問題。你可以試試看下面步驟
1. 把humix-conversation-module 搬到別的資料夾，讓它不會自動啟動 (放在core資料夾下的module 都會自動啟動）
    mv humix-sense/modules/core/humix-conversation-module ~/
2. 啟動humix-sense 
    source ~/start.sh
3. 在另一個terminal console啟動 humix-conversation-module
     cd ~/humix-conversation-module
     npm start

然後看看有沒有什麼error message ?

Thanks ~

**Comment by ChouYuWei** [comment]
您好，在source ~/start.sh部分，到了執行npm start 的時候開始出現錯誤，[ERROR] Humix-Sense: connection with module humix-conversation-module failed。

在npm start部分的看起來似乎是，程式執行時，抓錯config.js的感覺，itri那裏的speaker我設的是bruce不是Angela，錯誤訊息如下：
> humix-conversation-module@0.1.0 start /home/pi/humix-conversation-module
> node humix-conversation.js

creating logger, consolelevel:debug
2017-01-25T10:24:16.155Z [ INFO] humix-conversation-module: creating HumixSense communication
2017-01-25T10:24:16.331Z [ INFO] humix-conversation-module: using config: {"moduleName":"humix-conversation-module","commands":["tts"],"events":["stt"],"log":{"file":"humix-conversation-module.log","fileLevel":"info","consoleLevel":"debug"}}
========= starting ===========
2017-01-25T10:24:16.418Z [ INFO] humix-conversation-module: module registration completed
2017-01-25T10:24:16.422Z [DEBUG] humix-conversation-module: subscribing command topic:humix.sense.humix-conversation-module.command.tts
2017-01-25T10:24:16.437Z [ INFO] humix-conversation-module: access config
2017-01-25T10:24:16.443Z [ INFO] humix-conversation-module: loading config: {"lang":"en","stt-engine":"watson","tts-engine":"watson","stt":{"watson":{"username":"","passwd":""},"google":{"username":"","passwd":"","googleCredentialFile":"/home/pi/.humix/humix-stt.json","googleProjectName":"humix-stt","googleLan":"cmn-Hant-TW"}},"tts":{"watson":{"username":"","passwd":""},"iflytek":{"appid":"<app_id>"},"itri":{"username":"","passwd":"","speaker":"Angela"}}}
2017-01-25T10:24:16.445Z [ INFO] humix-conversation-module: Conversation instance created.
using config:{"lang":"en","stt-engine":"watson","tts-engine":"watson","stt":{"watson":{"username":"","passwd":""},"google":{"username":"","passwd":"","googleCredentialFile":"/home/pi/.humix/humix-stt.json","googleProjectName":"humix-stt","googleLan":"cmn-Hant-TW"}},"tts":{"watson":{"username":"","passwd":""},"iflytek":{"appid":"<app_id>"},"itri":{"username":"","passwd":"","speaker":"Angela"}}}
2017-01-25T10:24:16.448Z [ INFO] humix-conversation-module: Using stt-engine:watson
created waton stt instance
/home/pi/humix-conversation-module/node_modules/watson-developer-cloud/lib/base_service.js:78
        throw new Error('Argument error: username and password are required unless use_unauthenticated is set');
        ^
Error: Argument error: username and password are required unless use_unauthenticated is set
    at SpeechToTextV1.BaseService.initCredentials (/home/pi/humix-conversation-module/node_modules/watson-developer-cloud/lib/base_service.js:78:15)
    at SpeechToTextV1.BaseService (/home/pi/humix-conversation-module/node_modules/watson-developer-cloud/lib/base_service.js:45:18)
    at new SpeechToTextV1 (/home/pi/humix-conversation-module/node_modules/watson-developer-cloud/speech-to-text/v1.js:63:15)
    at Object.defineProperty.value (/home/pi/humix-conversation-module/node_modules/watson-developer-cloud/index.js:89:16)
    at WatsonSTT.init (/home/pi/humix-conversation-module/lib/stt/watson-stt.js:41:28)
    at Conversation.init (/home/pi/humix-conversation-module/lib/conversation.js:124:24)
    at HumixSense.<anonymous> (/home/pi/humix-conversation-module/humix-conversation.js:49:18)
    at emitOne (events.js:77:13)
    at HumixSense.emit (events.js:169:7)
    at /home/pi/humix-conversation-module/node_modules/humix-sense/index.js:264:14

npm ERR! Linux 4.4.11-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v4.2.6/bin/node" "/home/pi/.nvm/versions/node/v4.2.6/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! humix-conversation-module@0.1.0 start: `node humix-conversation.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the humix-conversation-module@0.1.0 start script 'node humix-conversation.js'.
npm ERR! This is most likely a problem with the humix-conversation-module package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node humix-conversation.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls humix-conversation-module
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/humix-conversation-module/npm-debug.log
pi@raspberrypi:~/humix-conversation-module $

**Comment by ChouYuWei** [comment]
剛剛發現在source ~/start.sh的部分，有以下訊息：
[ INFO] Humix-Sense: Init Humix Sense. Using Think URL:http://humix-baymax.mybluemix.net
[ INFO] Humix-Sense: Connected SenseId humix-pi to Think successfully.
以上這兩行，說明了真的抓錯 config.js，上面的Think URL是您之前Demo的baymax。另外我問一下，最開始建立的這個Humix Think網站，在 think 部分顯示 Not Started是正常的嗎?按照你的Guide說明，似乎是後續的步驟才要啟動?而在sense部分，在建立sense過後，重新整理頁面過後，也消失了，看來沒有真正的建立sense。

![humix-think_not_started](https://cloud.githubusercontent.com/assets/25160061/22291650/67f58898-e342-11e6-8ba5-4958edfe45c1.PNG)

**Comment by jeffffrey** [comment]
你設定的config.js 是 /home/pi/.humix/config.js 嗎？ 這個是優先讀取的config, 如果這個檔不存在，才會讀取humix-sense 資料夾下的config.js 

Think的部份 Not started 是不正常的，你可以試試看在bluemix 上重新restart application 嗎？

Please let me know how it works , thanks.

**Comment by ChouYuWei** [comment]
原來我設錯config.js，重新修改後，能連上了，不過還是有錯誤，如下圖
![20170129_humix-sense_ start sh-e](https://cloud.githubusercontent.com/assets/25160061/22402724/8b1df0ba-e63c-11e6-8972-06be48c2c64f.png)

猜想還是Humix Think網站沒有正常運作的關係。
重新啟動，我在bluemix 或cf上都試過，過程看起來好像正常，但結果還是Not Started。
![virtualbox_ubuntu_x64_16 04 1_29_01_2017_15_49_24-e](https://cloud.githubusercontent.com/assets/25160061/22402748/f6ba062e-e63c-11e6-8948-959e974c2807.png)

在新年中還回答我的問題，非常感謝，新年快樂。

**Comment by jeffffrey** [comment]
Sorry for late response :) 

你可以看一下 humix-settings.js 裡面，location 是不是設定成bluemix 嗎？ 可能是這個問題

**Comment by ChouYuWei** [comment]
humix-settings.js 裡面的location 改成bluemix 後，確實啟動了humix-think了。
![20170203_humix-think](https://cloud.githubusercontent.com/assets/25160061/22597699/a71ea86c-ea6b-11e6-908a-260828cb5454.PNG)

但是，要啟動 humix-sense時， ~/start.sh 還是出錯，跟前幾天那張圖一樣。
[ INFO] Humix-Sense: Init Humix Sense. Using Think URL:http://xxxx.mybluemix.net
[ERROR] Humix-Sense: Connection to Think is broken, message:

**Comment by jeffffrey** [comment]
幾個問題請教一下：

1. 你在RPI上，可以ping 到你humix-think 嗎？
2. 這個error message 只出現一兩次，還是會一直出現？
3. 有先在humix-think上建立一個sense-id, 然後在sense config.js設定一樣的id ? 

如果還是不行，麻煩貼完整的error message 我看一下。謝謝！

**Comment by ChouYuWei** [comment]
您真厲害，我這裡真的ping不到，我的設定出了點出錯誤，能ping 對外ip，沒發現ping不到站名，現在把humix-think建在bulemix部分ok了。

那再請教在ubuntu的local執行humix-think部分，counchdb 已安裝，humix-think在執行npm start時的錯誤如下：
![2017-02-08 18-29-37 _humix-think-npm_start](https://cloud.githubusercontent.com/assets/25160061/22733631/9043f6b8-ee2d-11e6-837e-b3cb2a4de03d.png)

最後能否在windows系統上執行humix-think? 謝謝。

**Comment by ChouYuWei** [comment]
我在humix-think上建立sense-id之後，本來以為是RasPi上還沒啟動，所以誤以為ok了，但是好像還是有些問題，我關機後下次再開或重整網頁之後，原本設定的id還是消失了，在node-red裡拉的sense-command的ID也沒有顯示我設的id。
![00_website_status-c](https://cloud.githubusercontent.com/assets/25160061/22759177/656901d6-ee8c-11e6-95bc-ce92fb6c7b02.png)

RasPi執行狀況如下：
sense 部分：
![01_sense_start-e](https://cloud.githubusercontent.com/assets/25160061/22759179/6a142f6c-ee8c-11e6-8c19-e745e393dee2.PNG)

conversation部分：
![02_conversation_start](https://cloud.githubusercontent.com/assets/25160061/22759203/85dec43c-ee8c-11e6-918a-8ec402ab5a53.PNG)

以上再麻煩您看一下，謝謝。

**Comment by jeffffrey** [comment]
你的系統要先裝node.js 的環境唷 
Error Message 看起來是沒有找到node, 建議用nvm 安裝
https://github.com/creationix/nvm

Humix Sense "理論上" 可以跑在windows, 但我自己沒有試過
你需要windows版的Nats server (官方網站上有提供)
Natsd 跑起來之後接下來的步驟就一樣了，你可以試試看

Sense ID 會不見的問題應該是 issue #5 , 你有試過restart bluemix application 嗎？ 通常restart 過一次應該就不會有這個問題。你試試看，如果有問題再update #5

**Comment by ChouYuWei** [comment]
1. Sense ID大概OK了。

2. 在 localhost 端，我確定有裝 node.js，node是可以執行的，下圖是我從 https://nodejs.org/en/download/ 下載安裝nodejs後，再用npm安裝 node-red(這個跟您提供的humix-think包含的node-red似乎不大一樣，並沒有包含waston的一些功能)，然後在Windows本機執行的畫面：
![00-e](https://cloud.githubusercontent.com/assets/25160061/22851945/4a0e7470-f06c-11e6-82d5-f1f772c6d5c0.PNG)

但是我在 humix-think裡執行 npm start 依然是有問題，不論ubuntu或是Windows，基本上錯誤訊息是一樣的。
![install_humix-think](https://cloud.githubusercontent.com/assets/25160061/22851968/f23f83e6-f06c-11e6-9f43-6f714ae2a1e2.PNG)

不知道是否相依的檔案路徑有問題? 謝謝。

**Comment by jeffffrey** [comment]
你試試在command line 直接打 `npm` and 'grunt' ，看能不能執行。另外你在local 要裝couchdb ，think才跑得起來

試試看，windows 目前還沒有正式支援，可能還會碰到其他問題。如果還有其他問題，請開新的issue。

如果你同意，我就先把這個關掉囉

**Comment by ChouYuWei** [comment]
ok，那這個討論串就先關閉吧，剩下的我先再試試看，謝謝您大力的協助。
