### ISSUE TITLE
humix-conversation-module 播放失敗

### ISSUE THREAD

**Issue by XiaoKaiRen** [project-humix/humix-think#14]
我使用humix 的 img 燒入進去PI
我在 PI 設置完 conversation-module 在 humix-sens 下 run start後
沒有出現錯誤但是講話後 conversation-module 沒有反應
所以我將 conversation-module 移出 core後執行 出現了
Error : Command failed: play -q /humix-sense/......./voice/processing.wav 
![image](https://user-images.githubusercontent.com/28284986/27983419-07ffa14e-63ee-11e7-8fee-735b4055458a.png)
 抱歉 因為使用HDIM連接PI 所以不方便截圖

**Comment by XiaoKaiRen** [comment]
後來發現  要使用 USB 麥克風+喇叭才可以使用
要如何修改設置呢?
如果要使用USB 麥克風 + 3.5喇叭 該如何設定呢?

**Comment by jeffffrey** [comment]
Can you try to follow step 3 in the following instructions ?  Let me know if that works for you. Thx. 

http://www.instructables.com/id/Build-a-Talking-Robot-With-Watson-and-Raspberry-Pi/

**Comment by XiaoKaiRen** [comment]
Thx ! 這個使用這個設定後就可以使用了
