### ISSUE TITLE
Cannot deploy this project to bluemix - gyp error

### ISSUE THREAD

**Issue by dkoh666** [project-humix/humix-think#4]
Hi there,

I am trying to deploy this to bluemix environment. configured as per instruction but it fails during staging phase. checking the log show node-gyp build consists of error. Please let me know where have i gone wrong. Thank you .Attached is the log files
[dkthink-err-log2.txt](https://github.com/project-humix/humix-think/files/419315/dkthink-err-log2.txt)

**Comment by jeffffrey** [comment]
Hi dkoh666, I think this problem should be fixed in #1 . Can you try the latest code on master branch and let me know if problem still exist ? Thanks.

**Comment by dkoh666** [comment]
Thanks Jeffrey. You are right the latest code on master branch works. Cheers!

**Comment by jeffffrey** [comment]
Thanks for the confirmation ! :)
